### PR TITLE
Agepr

### PR DESCRIPTION
**Pull request by ramirezfranciscof**
This PR incorporates two new tools for graph traversal:

1) AGE: this is a general purpose tool for graph traversal. It considers aiida nodes and groups as if they were both 'graph nodes' of an 'expanded graph', and generalizes the exploration of it by following certain 'rules'. This 'rules' are defined by using generic querybuilder instances: given an initial set of nodes, this queries will be successively applied on top of the results of the previous one, repeating the whole cycle the desired number of times (which could be 'until no new nodes are added').

2) traverse_graph: this is a simplified interface to use the AGE to search for aiida nodes and links using a reduced set of customizable rules. Contrary to the AGE, which retains basically the same versatility of the querybuilder and thus allows for very intricate traversals, in the graph traverse you can only specify which type of links will be allowed to be traversed and in which direction.

The function traverse_graph (which uses AGE as its search engine) is now used by the delete, the export  and the graph visualization procedures. The changes made are basically:

1) The `delete_nodes` function now uses the traverser instead of doing its own search (not a lot of performance gainz).

2) The `retrieve_linked_nodes` function (export) now uses the traverser instead of doing its own search (every node added to the set was queried separatedly for ancestors and descendants, now the whole set of new nodes found is queried for more nodes).

3) The graph class methods `recurse_descendants` and `recurse_ancestors` used to work by calling the `add_incoming` and `add_outgoing` many times. Now these are all independent and they all call the traverser (nodes were loaded to get their pks, now these are obtained directly from the query projection).

### CODE REVIEW

**Comment by ramirezfranciscof** [comment]
@ltalirz I've mentioned the actual functions changed for each feature, so you can test those directly if you prefer.

**Comment by ltalirz** [comment]
Thanks @ramirezfranciscof 

Test set: Exporting 67k groups with 5 nodes each (which expands to 1.4M nodes with provenance)

"Old implementation"[1]: ~450 minutes
AGE implementation: 6 minutes

Congratulations, this is a 75x speedup!

[1] This is on a modified version of the [progress bar PR](https://github.com/aiidateam/aiida-core/pull/3599), where I've already removed slow-down from the progress bar.
It took 5h 15min to retrieve the linked nodes for 70% of the nodes, then I canceled. I extrapolated from there for the total time.

**Comment by ltalirz** [comment]
I think this makes cleaning up and merging this PR a priority.

**Comment by ramirezfranciscof** [comment]
> Test set: Exporting 67k groups with 5 nodes each.
> 
> "Old implementation"[1]: ~450 minutes
> AGE implementation: 6 minutes
> 
> Congratulations, this is a 75x speedup!

Congrats AGEteam! @lekah @zooks97 Tomorrow I will discuss with @ltalirz and @sphuber which would be the best way to clean up the history for better reviewing/merging into develop.

**Comment by ltalirz** [comment]
@ramirezfranciscof Just to mention that I'm in Sion today, so no need to wait for me

**Pull request closed without merging**
